# ==================
# Project Details
# ==================
name: "jaffle_shop"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.1"
profile: "jaffle_shop"

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
clean-targets:
- "target"
- "dbt_modules"
- "logs"
- "dbt_packages"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
analysis-paths:
- "analysis"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  start_date: '2016-06-01'
  my_dbt_project:
    platforms:
    - web
    - mobile

# ==================
# Model Configs
# ==================
models:
  sub-project: {}

# ============
# Run Hooks
# ============
on-run-start:
- "{{ create_udfs() }}"
